version: '3.3'

services:

  redis_tls_buying:
    container_name: redis_tls_buying
    build:
      context: ./redis-sharding/redis-tls-container/
    ports:
      - "16399:16399"
    volumes:
      - ./redis-sharding/redis-tls-container/certs:/etc/certs
